version: '2'
services:
  order_db:
    ports:
      - 5432:5432
    image: postgres:latest
    container_name: order_db
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxim

  delivery_db:
    ports:
      - 5433:5432
    image: postgres:latest
    container_name: delivery_db
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxim

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  order-service:
    build:
      context: .
      dockerfile: dockerfiles/order/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://order_db:5432/order_db
      DB_USER: postgres
      DB_PASSWORD: maxim
      KAFKA_HOST: kafka:9092
    container_name: order-service
    depends_on:
      - order_db
      - kafka
    command: ["sh", "-c", "sleep 20 && java -jar orderapp.jar"]

  delivery-service:
    build:
      context: .
      dockerfile: dockerfiles/delivery/Dockerfile
    ports:
      - 8888:8888
    environment:
      DB_URL: jdbc:postgresql://delivery_db:5432/delivery
      DB_USER: postgres
      DB_PASSWORD: maxim
      KAFKA_HOST: kafka:9092
    container_name: delivery-service
    depends_on:
      - delivery_db
      - kafka
    command: ["sh", "-c", "sleep 40 && java -jar deliveryapp.jar"]

  mockuserservice:
    build:
      context: .
      dockerfile: dockerfiles/mockuserservice/Dockerfile
    ports:
      - 8085:8085
    container_name: mockuserservice
    command: [ "sh", "-c", "sleep 40 && java -jar test.jar" ]